apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: inside
    port: 9092
    targetPort: inside
  selector:
    app: kafka