apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: grafana-doppler-config
  namespace: monitoring
spec:
  tokenSecret:
    name: doppler-service-token
    namespace: monitoring
  project: monitoring
  config: prd
  managedSecret:
    name: grafana-env-from-doppler
    type: Opaque
