apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless # StatefulSet을 위한 Headless 서비스
  labels:
    app: zookeeper
spec:
  clusterIP: None # Headless
  ports:
  - name: client
    port: 2181
    targetPort: client
  - name: server
    port: 2888
    targetPort: server
  - name: leader-election
    port: 3888
    targetPort: leader-election
  selector:
    app: zookeeper 