apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc # Kafka 등이 Zookeeper에 접속할 때 사용할 서비스 이름
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      targetPort: client
  selector:
    app: zookeeper
