apiVersion: v1
kind: Secret
metadata:
  name: k3senv-application-db-credentials
type: Opaque
stringData:
  DB_HOST: "host"
  DB_PORT: "6543"
  DB_NAME: "postgres"
  SPRING_DATASOURCE_USERNAME: "username"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host:port/dbname"
