apiVersion: v1
kind: Service
metadata:
  name: k3senv-application-svc
  labels:
    app: k3senv-application
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: k3senv-application
