apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-env-application-doppler-config
  namespace: doppler-env-application
spec:
  tokenSecret:
    name: doppler-service-token
    namespace: doppler-env-application
  project: doppler-env-application
  config: prd
  managedSecret:
    name: doppler-env-application-env-from-doppler
    type: Opaque
