# 공통으로 사용했을 때, 정상적으로 작동하지 않아서 각 어플리케이션에서 처리하는 방법으로 변경

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-redirect-to-https
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
